# new feature
alpha = [
'ALBUS DUMBLEDORE',
'MINERVA MCGONAGALL',
'HARRY POTTER',
'REMUS LUPIN',
'RUBEUS HAGRID',
'HERMIONE GRANGER',
'SIRIUS BLACK',
'JAMES POTTER',
'PETER PETTIGREW',
'RON WEASLEY',
'GINNY WEASLEY',
'NEVILLE LONGBOTTOM',
'PARVATI PATIL',
'PERCY WEASLEY'
]

beta = [
'VOLDEMORT',
'SEVERUS SNAPE',
'SALAZAR SLYTHERIN',
'BELLATRIX LESTRANGE',
'HORACE SLUGHORN',
'REGULUS BLACK',
'LETA LESTRANGE',
'DOLORES UMBRIDGE',
'NARCISSA MALFOY',
'DRACO MALFOY',
'ALBUS SEVERUS POTTER',
'LUCIUS MALFOY'
]

gamma = [
'HELGA HUFFLEPUFF',
'BRIDGET WENLOCK',
'NEWT SCAMANDER',
'POMONA SPROUT',
'CEDRIC DIGGORY',
'NYMPHADORA TONKS',
'THE FAT FRIAR'
]

delta = [
'ROWENA RAVENCLAW',
'LUNA LOVEGOOD',
'GILDEROY LOCKHART',
'THE GREY LADY'
]
